### ISSUE TITLE
UUID Needed in SystemEntityList Entries 

### ISSUE THREAD

**Issue by clblais** [OpenC2SIM/C2SIMArtifacts#47]
### Issue Type

Problem Report

### Submitter Name

Tom van den Berg

### Contact Email

tom.vandenberg@tno.nl

### Submitter Organization

NLD

### Date of Submission

17 May 2023

### Product

LOX

### Description

There is no UUID for the systems in the LOX INI SystemEntityList (issue with schema).

### Consent

- [X] I agree to be contacted regarding this issue

**Comment by clblais** [comment]
The generated XML schema structure for SystemEntityList is given below:
	<xs:complexType name="SystemEntityListType">
		<xs:annotation>
			<xs:documentation>This is a listing of entities that reside within a system. The list defines what system a message should be sent to in order to get it to a given actor.  Each entity can reside on only one system. This list does not define necessarily define the complete list of entities on the given system.
Systems can build a map from this and other lists to get the system from a given entity.</xs:documentation>
			<xs:documentation>http://www.sisostds.org/ontologies/C2SIM#SystemEntityList</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="ActorReference" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element ref="SystemName" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

Solution to this may be to add another element to the sequence for the UUID of the entity in the list. [NOTE: There is a typo in the xs:documentation pulled from the ontology file -- "This list does not define necessarily define" should be changed to "This list does not necessarily define").]

**Comment by dr-cgf-home** [comment]
The definition shown above already says that a SystemEntityList defines the association of many entities (actors) to a single system. The Initialization Body has 1 or more SystemEntityLists-- so it could naturally have one SystemEntityList for each system in the coalition. That seems like a reasonable factoring of the information.

**Comment by dr-cgf-home** [comment]
A UUID is a string, and a SystemName is a string, so technically, the ontology already supports the use of UUIDs with systems. However, this usage of the string would have to be part of the coalition agreements for the exercise.  Was this not an adequate approach for CWIX 23?

Note;
Some coalitions might want to use other types of system name, such as host names or strings representing IP addresses. 
Making systems use a different identifier would require changing the C2SIMHeader (all of the properties referring to systems) as well as the SystemEntityList.

**Comment by clblais** [comment]
Proposed resolution to be presented in MSG-211 meeting Oct 11-13:
Add hasSystemUUID to SystemEntityList class declaration
In the C2SIM Core ontology:
Add new data property hasSystemUUID with range UUIDBase, annotated as “Unique identifier of a system participating in a C2SIM coalition of systems”; set as “Functional” (single-valued)
Add hasSystemUUID property axiom in class definition of SystemEntityList: hasSystemUUID exactly 1 UUIDBase

**Comment by clblais** [comment]
From discussions with members of MSG-201 and NETN FOM, it was agreed no change is needed to C2SIM. NETN v4 is planning to provide system name to identify a federate association to an entity or unit in the initialization file.
