### ISSUE TITLE
[C2SIM Issue Title]: Missing detection type code in Observation Report

### ISSUE THREAD

**Issue by beatrizMasa** [OpenC2SIM/C2SIMArtifacts#52]
### Issue Type

Problem Report

### Submitter Name

Beatriz Garmendia-Doval

### Contact Email

bgd@masagroup.net

### Submitter Organization

MASA Group

### Date of Submission

19 September 2023

### Product

C2SIM Core

### Description

The observation report needs to include optional detection information indicating if the observation is Discovery or Detection or Identification.

### Consent

- [X] I agree to be contacted regarding this issue

**Comment by dr-cgf-home** [comment]
The submitter of this issue should be contacted to explain more what the significance of "Discovery", "Detection," and "Identification" are. Sensor and target acquisition models often use "levels" of detection, originally (?) defined in Johnson's criteria for sensor performance:

> The minimum required resolution according to Johnson's criteria are expressed in terms of line pairs of [image resolution](https://en.wikipedia.org/wiki/Image_resolution) across a target, in terms of several tasks:[[3]](https://en.wikipedia.org/wiki/Johnson%27s_criteria#cite_note-3)

Detection, an object is present (1.0 +/− 0.25 line pairs)
Orientation, symmetrical, asymmetric, horizontal, or vertical (1.4 +/− 0.35 line pairs)
Recognition, the type object can be discerned, a person versus a car (4 +/− 0.8 line pairs)
Identification, a specific object can be discerned, a woman versus a man, the specific car (6.4 +/− 1.5 line pairs)

(See https://en.wikipedia.org/wiki/Johnson%27s_criteria#)

If so, what is "Discovery?"  We will have to consider whether C2SIM should include concepts from particular sensing/acquisition models as part of the standard.

**Comment by beatrizMasa** [comment]
I used Discovery, Detection, Identification as those were the codes defined in DetectionTypeCodeType in schema C2SIM_v9_SMX_LOX_ASX.xsd, I think added by the ASX extension. But I agree, the Detection, Recognition, Identification codes will be the correct ones to use. 
When an observation message is created because an unknown unit has been discovered, I would like to specify the level of detection. That way the C2 System will be able to represent the observed unit depending on the observation. For example an observed enemy infantry unit can be represented with the "unknown" symbol if just detected, with the enemy land unit symbol if recognized and with the enemy infantry symbol if identified. This does not specify the particulars of the sensors used to make those observations.

**Comment by dr-cgf-home** [comment]
Beatriz:  
The identification levels imply levels of specificity in the definition of target type. I imagine then that the ObservationReportContent would include a SubjectTypeObservation, and the EntityType in that observation would be an APP6-SIDC with some positions specified, and others left as wild cards. For example, 
SHGPUC-----****
to indicate a hostile land combat unit. This indicates the level of detection, and also actually specifies the symbol to use. Do you also need a code corresponding to an acquisition level?

**Comment by beatrizMasa** [comment]
I had not thought of using SubjectTypeObservation like that, if that works for the C2 systems receiving the reports, that's perfect. SWORD can add that information to the observation report.

**Comment by dr-cgf-home** [comment]
I suspect that the ontology will need some enhancements to capture additional terms used in Observation Reports-- to be determined. Also, there may be technical descriptions (for example, image data) that some systems provide that are currently out of the scope of C2SIM, and we will have to evaluate whether they should be included.
For this particular issue however, I propose that we include an example such as above in either the annotation for the SubjectTypeObservation or in a guidance document, but not change the ontology.

**Comment by beatrizMasa** [comment]
I agree. An example for the SubjectTypeObservation will be enough, no need to change the ontology. I will close the issue.
