### ISSUE TITLE
[C2SIM Issue Title]: C2SIM and Security

### ISSUE THREAD

**Issue by clblais** [OpenC2SIM/C2SIMArtifacts#67]
### Issue Type

Change Request

### Percieved Urgency

Urgent

### Submitter Name

Tom van den Berg

### Contact Email

tom.vandenberg@tno.nl

### Submitter Organization

TNO

### Date of Submission

24 November 2024

### Product

C2SIM Core

### Description

C2SIM and security. Authentication and authorization of clients is missing. Options: when using websocket or HTTP, the security token information can be provided in the HTTP header, as is commonly done. For TCP this is not possible and the token must be provided in the C2SIM message.  Thus, in general, the C2SIMHeaderType must be extended with an optional credentials element, containing two fields: type and data. Both of these need to be of type xsd:string.

### Consent

- [X] I agree to be contacted regarding this issue

**Comment by bruno-g** [comment]
Correction of issue done inside branch cwix-2025

**Comment by clblais** [comment]
Following the change, Tom van den Berg had the following comment: "To align with HLA4 naming (which uses type and data) I propose to use a Credentials element with two fields/subelements, namely: type and data. Since the name 'type' might cause problems for XML, these fields can also be named credentialsType and credentialsData."

This would change the names of the properties to hasCredentials, hasCredentialsType, and hasCredentialsData.

**Comment by clblais** [comment]
On Jan 28, 2025, Bruno contacted the originator (Tom van den Berg) to provide the rationale and source of the terminology used in the C2SIM change for this issue. Tom replied: "I withdraw my remark. Let’s stick to what you already have implemented."
